#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso MeshSmoother
wmake
wmake hexMeshSmoother

# ----------------------------------------------------------------- end	of-file
